### ISSUE TITLE
mod rewrite

### ISSUE THREAD

**Issue by shell1986** [Niyiojeyinka/PHP-AdsNetworkServer-#1]
Hi
The description says
then go to your_url / index.php / install to prepare the database for the web app

As far as I understand you use mod_rewrite
Can you tell me what settings you need to make?

**Comment by Niyiojeyinka** [comment]
hello,i guess you've resolved the issue ,in case you need any other help you can always get back to me

**Comment by shell1986** [comment]
Can you tell me how to create an administrator account?
When installing, the database is empty.

**Comment by Niyiojeyinka** [comment]
insert your details to team table. will do something about that in my next commit

**Comment by shell1986** [comment]
Can you tell what type of password encryption?
